export const SYNC_SESSION_SET = "SYNC_SESSION_SET";
export const SYNC_SESSION_CLEARED = "SYNC_SESSION_CLEARED";
export const SYNC_PARTY_SET = "SYNC_PARTY_SET";
export const SYNC_PENDING_REVIEW_SET = "SYNC_PENDING_REVIEW_SET";
export const SYNC_CARD_NOTICE_SET = "SYNC_CARD_NOTICE_SET";
