const STORAGE_TYPES = {
  LOCAL: "local",
  REMOTE: "remote",
};

const BOOLEAN_ENUM = {
  FALSE: 0,
  TRUE: 1,
};

const ENTRY_TYPES_SINGULAR = {
  INCOME: "income",
  EXPENSE: "expense",
};

const ENTRY_TYPES_PLURAL = {
  INCOMES: `${ENTRY_TYPES_SINGULAR.INCOME}s`,
  EXPENSES: `${ENTRY_TYPES_SINGULAR.EXPENSE}s`,
};

export {
  STORAGE_TYPES,
  BOOLEAN_ENUM,
  ENTRY_TYPES_PLURAL,
  ENTRY_TYPES_SINGULAR,
};
